### ISSUE TITLE
Not specify token in .vimrc, automatic PR fetching

### ISSUE THREAD

**Issue by Linuus** [joker1007/unite-pull-request#6]
Hi!

1. Is there any alternative to specifying a token in my vimrc?
I don't want to accidentally push it to my dotfiles repo.

2. Can this plugin automatically fetch the PR's for the current repo?
`:Unite pull_request` => Uses current repo ?

**Comment by joker1007** [comment]
Thanks for your proposal :smile: 

I implemented `2.  Can this plugin automatically fetch the PR's for the current repo?`
Please check latest README.

And, I think about token handling, but I don't found good solution yet.

**Comment by Linuus** [comment]
Ok, cool! Maybe have a look at how other plugins integrate? But maybe they use the same approach?

**Comment by joker1007** [comment]
I implemented token handling feature.
I refered to [gist-vim](https://github.com/mattn/gist-vim).

**Comment by joker1007** [comment]
refs https://github.com/joker1007/unite-pull-request/commit/4acafa8b9a95f03710b329f213afdfc37625dda3

**Comment by Linuus** [comment]
Very nice, thanks!
